TOREN_SCHAAK, NEUS, VRIJDAG13_A, ZAAG, TONG, RING_A, OGEN, OOR, ALIEN, RING_B, DOODSKIST, MAPS, BANG_GEZICHT_EMOJI, RING_C, \
    VRAAGTEKEN, ANDERHALVE_METER, KONINGIN_MET_KROON, EIFFEL_of_VUUR_TOREN, RING_D, VRIJDAG13_B, HARTEN_KONING, EEN, RING_E, \
    HALLOWEEN_POMPOEN, KONING_SCHAAK, HAAI, HAND, SST_GEZICHT = range(28)

alles = {TOREN_SCHAAK, NEUS, VRIJDAG13_A, ZAAG, TONG, RING_A, OGEN, OOR, ALIEN, RING_B, DOODSKIST, MAPS, BANG_GEZICHT_EMOJI, RING_C, \
         VRAAGTEKEN, ANDERHALVE_METER, KONINGIN_MET_KROON, EIFFEL_of_VUUR_TOREN, RING_D, VRIJDAG13_B, HARTEN_KONING, EEN, RING_E, \
         HALLOWEEN_POMPOEN, KONING_SCHAAK, HAAI, HAND, SST_GEZICHT}


ringen = { RING_A, RING_B, RING_C, RING_D, RING_E } #5
vrijdag = {VRIJDAG13_A, VRIJDAG13_B} #2

kroon = {ANDERHALVE_METER, KONINGIN_MET_KROON, KONING_SCHAAK} #3
schaakstukken = {TOREN_SCHAAK, KONING_SCHAAK} #2
koningshuis = {KONINGIN_MET_KROON, KONING_SCHAAK, HARTEN_KONING} #3
eng = {ALIEN, BANG_GEZICHT_EMOJI, HALLOWEEN_POMPOEN, HAAI, DOODSKIST} #5
zintuigen = {NEUS, OGEN, OOR, TONG, HAND} #5
een = {EEN} #1
torens = {TOREN_SCHAAK, EIFFEL_of_VUUR_TOREN} #2
vraagteken = {VRAAGTEKEN} #1
gezicht = {NEUS, OGEN, OOR, TONG} #4
handen = {HAND, SST_GEZICHT} #2
gereedschap = {ZAAG} #1
gezichten = {ALIEN, BANG_GEZICHT_EMOJI, KONINGIN_MET_KROON, SST_GEZICHT, HALLOWEEN_POMPOEN} #5
aag = {VRAAGTEKEN, ZAAG}
woorden_met_aa = {}
